### ISSUE TITLE
Can't bind to 'image-lazy-load-item' since it isn't a known native property

### ISSUE THREAD

**Issue by giejay** [NathanWalker/ng2-image-lazy-load#1]
I'm getting the following error, I included the directive and provider as follows:

import {IMAGELAZYLOAD_DIRECTIVES} from 'ng2-image-lazy-load/ng2-image-lazy-load';

@Component({
  selector: 'home',
  moduleId: module.id,
  templateUrl: './home.html',
  styleUrls: ['./home.css'],
  pipes: [ArraySortPipe],
  directives: [IMAGELAZYLOAD_DIRECTIVES]
})

In my template: 

`<img [image-lazy-load-item]="photo.url" class="img-thumbnail" alt=""/></a>`

My main.ts:
import {IMAGELAZYLOAD_PROVIDERS} from 'ng2-image-lazy-load/ng2-image-lazy-load';
bootstrap(AppCmp, [
  ROUTER_PROVIDERS, HTTP_PROVIDERS, IMAGELAZYLOAD_PROVIDERS,
  provide(APP_BASE_HREF, {useValue: '/'})
]);

Googling the error results in getting answers like you should include the directive, but I'm doing that..

**Comment by NathanWalker** [comment]
Thanks for posting this issue. I'm traveling back late tonight after long business trip and will get back with you soon. In meantime, could you reply back with a link to repo where you are trying this and I could take a look in more detail. Also maybe post back what your template looks like.

**Comment by NathanWalker** [comment]
Looks like you may be missing the container directive that should surround your items.

**Comment by NathanWalker** [comment]
From the README, you'll need the container div `image-lazy-load-area` surrounding the items:

```
<div image-lazy-load-area>
        <div *ng-for="#image of images">
          <img [image-lazy-load-item]="image.url"/>
        </div>
      </div>
```

**Comment by giejay** [comment]
I did add that container div, unfortunately that did not have any effect. 

I created a fork of the angular seed I'm using and added the code for lazy loading: https://github.com/giejay/angular2-seed

**Comment by NathanWalker** [comment]
@giejay Thank you for bringing this to my attention. A couple things are off, the README does not reflect latest changes and the library needs to be updated to beta.6... I'm making those changes now.
I'll have them complete shortly or at least by end of day Thursday.

**Comment by giejay** [comment]
Thanks!

**Comment by NathanWalker** [comment]
Ok @giejay version `1.1.1` is now available. Please try that (bump the version in your forks `package.json`, then `npm install` again) and refer back to the updated README here... main thing is to change your template to:

```
<div imageLazyLoadArea>
    <img [imageLazyLoadItem]="'assets/img/smile.png'"/>
</div>
```

Also it will be important to copy the `xhrWorker.js` file here:
https://github.com/NathanWalker/ng2-image-lazy-load/blob/master/src/assets/js/xhrWorker.js
And place it here in your fork:
https://github.com/giejay/angular2-seed/tree/master/src/assets/js/

You'll need to create the `js` folder to put the file into.
This is mentioned in the `README`.

Give that a try; should get ya going :+1:  lemme know or close this if all is good after this, thanks.

**Comment by giejay** [comment]
Thank you for the quick fix!

The directive error is gone, now a new error occurs:

TypeError: Observable_1.Observable.fromEvent(...).debounceTime is not a function

I pushed my changes to my fork

Its in this function:
 ImageLazyLoadArea.prototype.scrollSubscribe = function () {
        var _this = this;
        var scrollStream = Observable_1.Observable.fromEvent(window, 'scroll').debounceTime(250);
        this.scrollSubscription = scrollStream.subscribe(function () {
            _this.loadInView();
        });
    };

**Comment by NathanWalker** [comment]
Ah yes but of course. Just published `1.1.2` with the fix for that. Bump and try once more! ;)

**Comment by giejay** [comment]
It works perfectly now! Just one other question, is it possible to widen the scope of the window of the images which are loaded? Now I'm seeing a lot of empty divs when scrolling, is there a config available to load them a bit earlier?

**Comment by NathanWalker** [comment]
Yes! try doing this:

```
<div imageLazyLoadArea="200">
    <img [imageLazyLoadItem]="'assets/img/smile.png'"/>
</div>
```

This will set the threshold to start loading images with 200 pixel offset from the bottom of the window.
Play with that number.

**Comment by NathanWalker** [comment]
I'll close this as it sounds like you have it working now, but feel free to comment back if you have any other issues or open a separate issue if you find something else. Thanks!

**Comment by NathanWalker** [comment]
@giejay Did you get the offset working for your needs?

**Comment by giejay** [comment]
Yes it works great, thank you!
