### ISSUE TITLE
Angular2 HTTP Service loading by default

### ISSUE THREAD

**Issue by mrStudent123** [NathanWalker/ng2-image-lazy-load#11]
It would be nice to be able to replace the webworker requests with standard angular2 http service requests, as for example i have included my custom http implementation during app bootstrap for authentication calls. Another way to do this would be to add a possibility to pass custom headers to the directive (or configure it once in the app component)

**Comment by NathanWalker** [comment]
With `2.0.7` you can now disable WebWorkers with:

```
import {WebWorkerService} from 'ng2-image-lazy-load';

// default: true
// set to false if you want to force Http instead of WebWorker
WebWorkerService.enabled = false;
```

**Comment by NathanWalker** [comment]
You can now also pass custom headers for each image request, see this:
https://github.com/NathanWalker/ng2-image-lazy-load#configuration
