### ISSUE TITLE
Not working with RC5/RC6

### ISSUE THREAD

**Issue by smyth64** [NathanWalker/ng2-image-lazy-load#12]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**

_What steps should we try in your demo to see the problem?_

**Current behavior**
When I include the module in an RC6 Project I get this error.

![image](https://cloud.githubusercontent.com/assets/3246782/18354039/7f9d5578-75e4-11e6-9899-4fd59bd6f99a.png)

**Expected/desired behavior**

**Other information**

**Comment by smyth64** [comment]
This project is dead!

**Comment by NathanWalker** [comment]
Lol. Certainly needs some attn; I'll work on this tomorrow. Got to, plus our company app needs this lib!

**Comment by NathanWalker** [comment]
Latest `2.0.6` works with Angular 2 Final now. Please see updated [README](https://github.com/NathanWalker/ng2-image-lazy-load#example-implementation) for usage instructions.

**Comment by smyth64** [comment]
Yeah awesome Nathan! :) Thank you so much!
