### ISSUE TITLE
Uncaught ReferemceError: __decorate is not defined

### ISSUE THREAD

**Issue by stefanfr** [NathanWalker/ng2-image-lazy-load#15]
Hello,

I ran in some problems i'm trying to fix for the last hours but cant figure it out.
I hope someone here can help me out or confirm it is a bug/issue

here are the error's i'm getting:
https://s14.postimg.org/ggo9hmq1r/Screen_Shot_2016_10_10_at_11_29_04.png

**Comment by RedEars** [comment]
I have the same problem

**Comment by jinder** [comment]
It's because the library has been built with the TypeScript "noEmitHelpers" flag.  To fix it, add the 'ts-helpers' library and set this flag to true in your own tsconfig.json.

See here for details:  https://github.com/ngParty/ts-helpers

**Comment by NathanWalker** [comment]
@jinder thank you! Yes indeed it was.
I have been going back/forth on which is best.

@stefanfr @RedEars  I went ahead and published `2.0.9` with the emithelpers back on so pull the latest patch and see if that helps you get past that issue.

**Comment by RedEars** [comment]
@NathanWalker  No, this problem still exists on version 2.0.9. 
But with the fix from @jinder it actually works

**Comment by calvinmuller** [comment]
I still can't get this to work, using angular-cli tried @jinder solution and using the latest commit.

**Comment by YonatanKra** [comment]
Just saw this one after posting #20. I've downloaded the latest version (2.0.9) with no success.
@jinder your trick works :)

**Comment by NathanWalker** [comment]
I'll try to get this working this week (busy back after holidays), if anyone knows a fix, a PR would be greatly appreciated 👍

**Comment by snortblt** [comment]
This issue is closed but persists in 2.0.9. Any updates? This info at the link @jinder provided doesn't appear to resolve the issue: 

> NOTE: Starting Typescript 2.1 this package won't be needed anymore
> Instead you can provide --importHelpers together with --noEmitHelpers which will import emit helpers from Typescript "tslib"

**Comment by jinder** [comment]
I don't use this library any more, but it should be built with noEmitHelpers set as true, and when you import the library make sure you've included the tslib polyfill (included by default with an angular-cli project).

**Comment by snortblt** [comment]
Thanks @jinder. That's what I've got. Now it complains that __extends is not defined instead.
