### ISSUE TITLE
Error when installing 

### ISSUE THREAD

**Issue by miraclemaker** [NathanWalker/ng2-image-lazy-load#2]
I get an error when running npm install on Windows 7:
## [17:15:19] Requiring external module ts-node/register

? Unable to compile TypeScript

tools\utils\server.ts (2,31): Cannot find module 'open'. (2307)
tools\utils\template_injectables.ts (1,1): File 'D:/www/repo/firefly/supercard/n
g2-image-lazy-load-master/tools/manual_typings/slash.d.ts' not found. (6053)
## tools\utils\template_injectables.ts (3,24): Cannot find module 'slash'. (2307)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\miraclemaker\Ap
pData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! ng2-image-lazy-load@1.1.2 postinstall: `typings install && gulp check.v
ersions && npm prune`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-image-lazy-load@1.1.2 postinstall script 'typings ins
tall && gulp check.versions && npm prune'.
npm ERR! This is most likely a problem with the ng2-image-lazy-load package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune
npm ERR! You can get their info via:
npm ERR!     npm owner ls ng2-image-lazy-load
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\www\repo\firefly\supercard\ng2-image-lazy-load-master\src\npm-de
bug.log

**Comment by miraclemaker** [comment]
Node is version 4.2.6, npm is 3.3.9

**Comment by NathanWalker** [comment]
sounds like you are trying to run the demo locally? is that correct?

**Comment by NathanWalker** [comment]
Following this I presume?
https://github.com/NathanWalker/ng2-image-lazy-load/blob/master/CONTRIBUTING.md#how-to-get-setup-and-run-the-code-as-well-as-test

**Comment by miraclemaker** [comment]
Yes this was trying to run the sample project. Yes I followed the instructions in the guide with the same result. Strangely I'm using the angular2 seed project in another project with no problems.

**Comment by NathanWalker** [comment]
You might try a fresh setup:

```
rm -rf node_modules
npm install
npm start
```

If that still fails, you may want to try installing https://github.com/coreybutler/nvm-windows ... and try installing the node 4.2.6 w/ npm 2.14.12 pair.... or node 5.5.0 w/ npm 3.5.x pair...
I've tested with both of those and they work.

4.2.6 w/ npm 3.3.9 could be an issue, not sure.

**Comment by miraclemaker** [comment]
Thanks I was able to get it working with my existing project by running
    npm install ng2-image-lazy-load --save
Then following the code example in the demo - many thanks for your help.

**Comment by NathanWalker** [comment]
Excellent, glad you got it working. Thanks for letting me know!
