### ISSUE TITLE
Ionic 2 Uncaught ReferenceError: __decorate

### ISSUE THREAD

**Issue by partharanjan** [NathanWalker/ng2-image-lazy-load#31]
![image](https://cloud.githubusercontent.com/assets/1378330/23479136/786f428c-fee9-11e6-9d8e-92a99fcb566d.png)

Uncaught ReferenceError: __decorate is not defined
    at web-worker.service.js:50

on ionic 2

**Comment by NathanWalker** [comment]
Dupe: https://github.com/NathanWalker/ng2-image-lazy-load/issues/31
There is a solution posted there, however a full solution will come in time, just busy at moment unfortunately.
