### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by TeodorKolev** [NathanWalker/ng2-image-lazy-load#32]
I have problems running the plugin. I use this [cli](https://github.com/AngularClass/angular2-webpack-starter). I have add
```
import { ImageLazyLoadModule, WebWorkerService } from "ng2-image-lazy-load";
  imports: [ // import Angular's modules
 ...
    ImageLazyLoadModule,
  ...
    }),
    ...
  ],
```
and (which I am not sure is this the problem)
`WebWorkerService.workerUrl = '../assets/js/xhrWorker.js';`
[here](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.module.ts). At the html of my Component I have only this:
```
<div imageLazyLoadArea>
    <div>
      <img [imageLazyLoadItem]="img" alt="{{ name }}">
    </div>
</div>
```
where "img" and "name" are @Inputs from parent Component. Does my mistake is way of import of xhrWorker.js file?
(I do have included)
```
import { BrowserModule } from '@angular/platform-browser';
import {HttpModule, Http} from '@angular/http';
```
I don't see any errors in console. Should I have to add anything in webpack?

**Comment by NathanWalker** [comment]
@TeodorKolev did you try setting CSS or explicit height on the surrounding div or img?

**Comment by TeodorKolev** [comment]
Nope, but I did try using another plugin, which works

**Comment by NathanWalker** [comment]
Excellent 👍
