### ISSUE TITLE
Images doesnt load

### ISSUE THREAD

**Issue by royipressburger** [NathanWalker/ng2-image-lazy-load#6]
Hi

Im trying to use the directive and for some reason the images doesn't load at all.

I did exactly as mention on [this issue](https://github.com/NathanWalker/ng2-image-lazy-load/issues/4).

When trying to debug it I see that the `ImageLazyLoader` constructor is getting a worker as a parameter, and it always a `WebWorker` object with an empty `activeWorkers` array

any ideas?

ps: When using normal src on the image everything works

**Comment by NathanWalker** [comment]
Hi @royipressburger could you provide your component and template setup here?

**Comment by NathanWalker** [comment]
I also need to update this to use rc.1 ... I'll try to do that soon.

**Comment by royipressburger** [comment]
Yo @NathanWalker 
This is the html:

``` html
<ion-card>
  <ion-item>
    <ion-avatar item-left>
      <ion-img src="{{event.profileImage}}"></ion-img>
    </ion-avatar>
    <h3 >{{event.firstName}}</h3>
    <h3 >{{event.title}}</h3>
  </ion-item>

  <ion-img [imageLazyLoadItem]="event.coverPhoto"></ion-img>
</ion-card>
```

Also tried the same html with `<img>` and not `<ion-img>` and with `{{photo}}`

this is the componenet:

``` js
import {Component, Input, Output, EventEmitter} from "angular2/core";
import {IONIC_DIRECTIVES} from "ionic-angular";
import {TimeAgoPipe} from 'angular2-moment/TimeAgoPipe';
import {IMAGELAZYLOAD_DIRECTIVES, WebWorker} from 'ng2-image-lazy-load/ng2-image-lazy-load';

@Component({
    selector: "tra-trip-card",
    templateUrl: "build/components/trip-card/trip-card.html",
    pipes: [TimeAgoPipe],
    directives: [IONIC_DIRECTIVES, IMAGELAZYLOAD_DIRECTIVES],
})
export class TraTripCard {
  @Input() event;

  constructor() {
    WebWorker.workerUrl = 'build/assets/xhrWorker.js';
  }
}
```

`IMAGELAZYLOAD_PROVIDERS` is being injected in the app file after the `http` service

Another thing that might be related is that im using an `http` provider that is not the default of angualr2
Im using some library that extends the default http, again not sure is related but just FYI ([here is the lib](https://github.com/ronzeidman/ng2-ui-auth)

And im currently using angular beta 15 (this is what is supported with the current ionic 2 version)

**Comment by NathanWalker** [comment]
Change view to:

```
<ion-card imageLazyLoadArea>
  <ion-item>
    <ion-avatar item-left>
      <ion-img src="{{event.profileImage}}"></ion-img>
    </ion-avatar>
    <h3 >{{event.firstName}}</h3>
    <h3 >{{event.title}}</h3>
  </ion-item>

  <ion-img [imageLazyLoadItem]="event.coverPhoto"></ion-img>
</ion-card>
```

The `imageLazyLoadArea` is important to have on parent container. You only need that once on the parent of any number of `[imageLazyLoadItem]`'s 👍

**Comment by royipressburger** [comment]
Hi again, @NathanWalker 

So yes i probably missed that in the documentation.
But now i have some other problem:
The photos I try to load are stored in aws s3, I see the request is being made to get the photo I get back status code 200 but the image is not dispalyed. 

When I look at the reqests with the `src` and with the `imageLazyLoadItem` I see only one different and its with the `Accept` header being sent in the request

here is the request 
![selection_005](https://cloud.githubusercontent.com/assets/9999184/15337652/66d15b88-1c85-11e6-85ce-7e9d2f983387.png)

Thanks again

**Comment by NathanWalker** [comment]
I'm not 100% familiar with Ionic elements like `ion-img`  but you will need to have proper styling on it.
Since the lib looks for an actual `IMG` node for `src` replacement, in this case it's `ion-img` so would be adding inline `style` as `background-image` and in those cases, it would need height and width set to see it.

Just to see, inspect element, find that `ion-img` and set explicity height and width to see if the image starts to appear.

**Comment by royipressburger** [comment]
Ok Cool.. working with `img`, I'll look for a solution for `ion-img`.
Thanks!

**Comment by NathanWalker** [comment]
Cool! Keep me posted as I would definitely be interested to know!
