### ISSUE TITLE
Ionic 2 Support

### ISSUE THREAD

**Issue by eusthace811** [NathanWalker/ng2-image-lazy-load#7]
Hi Nathan, You've done an amazing job!
Can I ask you to a way to integrate your webworker within an Ionic 2 app?
I am trying to find your webworker in order to copy and setup in my Ionic 2 without success.

Ohh, Found I need to change the import to:

import {IMAGELAZYLOAD_PROVIDERS, WebWorkerService} from 'ng2-image-lazy-load/ng2-image-lazy-load';

And:
WebWorkerService.workerUrl = 'js/xhrWorker.js';

**Comment by jlsuarezs** [comment]
I am getting this error all the time:
Cannot set property 'workerUrl' of undefined
:S

**Comment by jlsuarezs** [comment]
Ohh, Found I need to change the import to:

import {IMAGELAZYLOAD_PROVIDERS, WebWorkerService} from 'ng2-image-lazy-load/ng2-image-lazy-load';

And:
WebWorkerService.workerUrl = 'js/xhrWorker.js';

**Comment by jlsuarezs** [comment]
But now the cross-origin problem...:(

**Comment by cozzbie** [comment]
Hi @jlsuarezs does this work as expected in your ionic project?

**Comment by NathanWalker** [comment]
Verified this works in Ionic 2 with latest release.
Please let me know if you encounter any further issues using with Ionic.
