### ISSUE TITLE
Not working with Webpack

### ISSUE THREAD

**Issue by smyth64** [NathanWalker/ng2-image-lazy-load#8]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
Use Angular 2 Webpack Starter

_What steps should we try in your demo to see the problem?_
I included everything like in your demo but it doesn't work. It's not loading the image and I see a lot of notifications in the console.

**Current behavior**
![image](https://cloud.githubusercontent.com/assets/3246782/16213517/3aa4b02e-3750-11e6-885c-80369334f6dc.png)

**Expected/desired behavior**

**Other information**

**Comment by NathanWalker** [comment]
Latest `2.0.6` works with Angular 2 Final and webpack 👍
