### ISSUE TITLE
Where is assets/js/xhrWorker.js?

### ISSUE THREAD

**Issue by smyth64** [NathanWalker/ng2-image-lazy-load#9]
You told, that we can copy this file. But where is it? :)

**Comment by vandres** [comment]
I found it https://ng2-image-lazy-load-demo.herokuapp.com/dist/xhrWorker.js

**Comment by shadeeka** [comment]
i have followed all the instructions and use xhrWorker.js as well, but i couldn't load images from component view,
but using
`ImageLazyLoaderService.load('url')` gives me true result
can anyone please help me to find why it is not working in html file

thank you

**Comment by ventr1x** [comment]
Sadly just another plugin with no support whatsoever.
I am also unable to get it to work (it works manually with the webworker).
As there is no error, exception, log or further documentation at all, it would be easier to implement the entire thing myself than sift through 3rd party code from some dev which skill I can't asses before doing that.
Gotta love the javascript eco system!

**Comment by NathanWalker** [comment]
@ventr1x Definitely takes a collective effort of support with OSS. 
I will try to update the lib this upcoming week. Been hard with the constantly changing angular rc releases and breaking changes. Sounds like rc.5 should be last big round of breaking changes so it should now be worth updating this lib to latest. In doing so, I'll make sure the webworker file ends up here.

**Comment by NathanWalker** [comment]
Latest `2.0.6` works with Angular 2 Final. Also, the `xhrWorker.js` file can be downloaded here:
https://github.com/NathanWalker/ng2-image-lazy-load/blob/master/src/public/xhrWorker.js
